title: "Iván's Blog"
author: "Iván Cedó"
description: "This is a cybersecurity blog." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names:
email: "ivancedo09@gmail.com"
github_username: "ivancedo"

#####################################################
######### Nothing below needs to be changed #########
#####################################################
theme: "minima"

#rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
